version: '3.4'

services:

    postgres:
        image: postgres:15.3
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin            
        logging:
          options:
            max-size: 10m
            max-file: "3"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - postgres-network
            
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            # AMQP 
            - 5672:5672
            # HTTP
            - 15672:15672
        volumes:
            - rabbitmq_data:/data
            
            
networks:
    postgres-network:
        driver: bridge

volumes:
    postgres_data:    
        driver: local
        
    rabbitmq_data:
        driver: local